# Generated by Django 4.2.5 on 2024-01-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee_model',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
